// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserToken = `-- name: AddUserToken :one
INSERT INTO tokens (id,provider,username,email,avatarURL,token,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, provider, username, email, token, avatarurl, created_at
`

type AddUserTokenParams struct {
	ID        uuid.UUID `json:"id"`
	Provider  string    `json:"provider"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Avatarurl string    `json:"avatarurl"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddUserToken(ctx context.Context, arg AddUserTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, addUserToken,
		arg.ID,
		arg.Provider,
		arg.Username,
		arg.Email,
		arg.Avatarurl,
		arg.Token,
		arg.CreatedAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Username,
		&i.Email,
		&i.Token,
		&i.Avatarurl,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTokens = `-- name: GetAllTokens :many
SELECT id, provider, username, email, token, avatarurl, created_at from tokens
`

func (q *Queries) GetAllTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Username,
			&i.Email,
			&i.Token,
			&i.Avatarurl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many

SELECT DISTINCT username FROM tokens WHERE provider= ($1)
`

// -- name: GetQueue :many
// SELECT id,title,artist,requested_by FROM queue WHERE channel =($1);
func (q *Queries) GetUsers(ctx context.Context, provider string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateToken = `-- name: ValidateToken :many
SELECT username,email,avatarURL FROM tokens WHERE token = ($1)
`

type ValidateTokenRow struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Avatarurl string `json:"avatarurl"`
}

func (q *Queries) ValidateToken(ctx context.Context, token string) ([]ValidateTokenRow, error) {
	rows, err := q.db.QueryContext(ctx, validateToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidateTokenRow
	for rows.Next() {
		var i ValidateTokenRow
		if err := rows.Scan(&i.Username, &i.Email, &i.Avatarurl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
